// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto
package com.dsky.netty.pvpser.test.protobuf;
public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CMsg)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string msghead = 1;</code>
     */
    boolean hasMsghead();
    /**
     * <code>required string msghead = 1;</code>
     */
    java.lang.String getMsghead();
    /**
     * <code>required string msghead = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgheadBytes();

    /**
     * <code>required string msgbody = 2;</code>
     */
    boolean hasMsgbody();
    /**
     * <code>required string msgbody = 2;</code>
     */
    java.lang.String getMsgbody();
    /**
     * <code>required string msgbody = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgbodyBytes();
  }
  /**
   * Protobuf type {@code CMsg}
   */
  public  static final class CMsg extends
      com.google.protobuf.GeneratedMessageLite<
          CMsg, CMsg.Builder> implements
      // @@protoc_insertion_point(message_implements:CMsg)
      CMsgOrBuilder {
    private CMsg() {
      msghead_ = "";
      msgbody_ = "";
    }
    private int bitField0_;
    public static final int MSGHEAD_FIELD_NUMBER = 1;
    private java.lang.String msghead_;
    /**
     * <code>required string msghead = 1;</code>
     */
    public boolean hasMsghead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string msghead = 1;</code>
     */
    public java.lang.String getMsghead() {
      return msghead_;
    }
    /**
     * <code>required string msghead = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgheadBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(msghead_);
    }
    /**
     * <code>required string msghead = 1;</code>
     */
    private void setMsghead(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      msghead_ = value;
    }
    /**
     * <code>required string msghead = 1;</code>
     */
    private void clearMsghead() {
      bitField0_ = (bitField0_ & ~0x00000001);
      msghead_ = getDefaultInstance().getMsghead();
    }
    /**
     * <code>required string msghead = 1;</code>
     */
    private void setMsgheadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      msghead_ = value.toStringUtf8();
    }

    public static final int MSGBODY_FIELD_NUMBER = 2;
    private java.lang.String msgbody_;
    /**
     * <code>required string msgbody = 2;</code>
     */
    public boolean hasMsgbody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string msgbody = 2;</code>
     */
    public java.lang.String getMsgbody() {
      return msgbody_;
    }
    /**
     * <code>required string msgbody = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgbodyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(msgbody_);
    }
    /**
     * <code>required string msgbody = 2;</code>
     */
    private void setMsgbody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      msgbody_ = value;
    }
    /**
     * <code>required string msgbody = 2;</code>
     */
    private void clearMsgbody() {
      bitField0_ = (bitField0_ & ~0x00000002);
      msgbody_ = getDefaultInstance().getMsgbody();
    }
    /**
     * <code>required string msgbody = 2;</code>
     */
    private void setMsgbodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      msgbody_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getMsghead());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getMsgbody());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getMsghead());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getMsgbody());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static Msg.CMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Msg.CMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Msg.CMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Msg.CMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Msg.CMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Msg.CMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Msg.CMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Msg.CMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Msg.CMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Msg.CMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Msg.CMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code CMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Msg.CMsg, Builder> implements
        // @@protoc_insertion_point(builder_implements:CMsg)
        Msg.CMsgOrBuilder {
      // Construct using Msg.CMsg.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string msghead = 1;</code>
       */
      public boolean hasMsghead() {
        return instance.hasMsghead();
      }
      /**
       * <code>required string msghead = 1;</code>
       */
      public java.lang.String getMsghead() {
        return instance.getMsghead();
      }
      /**
       * <code>required string msghead = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgheadBytes() {
        return instance.getMsgheadBytes();
      }
      /**
       * <code>required string msghead = 1;</code>
       */
      public Builder setMsghead(
          java.lang.String value) {
        copyOnWrite();
        instance.setMsghead(value);
        return this;
      }
      /**
       * <code>required string msghead = 1;</code>
       */
      public Builder clearMsghead() {
        copyOnWrite();
        instance.clearMsghead();
        return this;
      }
      /**
       * <code>required string msghead = 1;</code>
       */
      public Builder setMsgheadBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMsgheadBytes(value);
        return this;
      }

      /**
       * <code>required string msgbody = 2;</code>
       */
      public boolean hasMsgbody() {
        return instance.hasMsgbody();
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public java.lang.String getMsgbody() {
        return instance.getMsgbody();
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgbodyBytes() {
        return instance.getMsgbodyBytes();
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public Builder setMsgbody(
          java.lang.String value) {
        copyOnWrite();
        instance.setMsgbody(value);
        return this;
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public Builder clearMsgbody() {
        copyOnWrite();
        instance.clearMsgbody();
        return this;
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public Builder setMsgbodyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMsgbodyBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CMsg)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Msg.CMsg();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasMsghead()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasMsgbody()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Msg.CMsg other = (Msg.CMsg) arg1;
          msghead_ = visitor.visitString(
              hasMsghead(), msghead_,
              other.hasMsghead(), other.msghead_);
          msgbody_ = visitor.visitString(
              hasMsgbody(), msgbody_,
              other.hasMsgbody(), other.msgbody_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  msghead_ = s;
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  msgbody_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Msg.CMsg.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CMsg)
    private static final Msg.CMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CMsg();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Msg.CMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CMsg> PARSER;

    public static com.google.protobuf.Parser<CMsg> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CMsgHeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CMsgHead)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 msglen = 1;</code>
     */
    boolean hasMsglen();
    /**
     * <code>required int32 msglen = 1;</code>
     */
    int getMsglen();

    /**
     * <code>required int32 msgtype = 2;</code>
     */
    boolean hasMsgtype();
    /**
     * <code>required int32 msgtype = 2;</code>
     */
    int getMsgtype();

    /**
     * <code>required int32 msgseq = 3;</code>
     */
    boolean hasMsgseq();
    /**
     * <code>required int32 msgseq = 3;</code>
     */
    int getMsgseq();

    /**
     * <code>required int32 termversion = 4;</code>
     */
    boolean hasTermversion();
    /**
     * <code>required int32 termversion = 4;</code>
     */
    int getTermversion();

    /**
     * <code>required int32 msgres = 5;</code>
     */
    boolean hasMsgres();
    /**
     * <code>required int32 msgres = 5;</code>
     */
    int getMsgres();

    /**
     * <code>required string termid = 6;</code>
     */
    boolean hasTermid();
    /**
     * <code>required string termid = 6;</code>
     */
    java.lang.String getTermid();
    /**
     * <code>required string termid = 6;</code>
     */
    com.google.protobuf.ByteString
        getTermidBytes();
  }
  /**
   * Protobuf type {@code CMsgHead}
   */
  public  static final class CMsgHead extends
      com.google.protobuf.GeneratedMessageLite<
          CMsgHead, CMsgHead.Builder> implements
      // @@protoc_insertion_point(message_implements:CMsgHead)
      CMsgHeadOrBuilder {
    private CMsgHead() {
      termid_ = "";
    }
    private int bitField0_;
    public static final int MSGLEN_FIELD_NUMBER = 1;
    private int msglen_;
    /**
     * <code>required int32 msglen = 1;</code>
     */
    public boolean hasMsglen() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 msglen = 1;</code>
     */
    public int getMsglen() {
      return msglen_;
    }
    /**
     * <code>required int32 msglen = 1;</code>
     */
    private void setMsglen(int value) {
      bitField0_ |= 0x00000001;
      msglen_ = value;
    }
    /**
     * <code>required int32 msglen = 1;</code>
     */
    private void clearMsglen() {
      bitField0_ = (bitField0_ & ~0x00000001);
      msglen_ = 0;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private int msgtype_;
    /**
     * <code>required int32 msgtype = 2;</code>
     */
    public boolean hasMsgtype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 msgtype = 2;</code>
     */
    public int getMsgtype() {
      return msgtype_;
    }
    /**
     * <code>required int32 msgtype = 2;</code>
     */
    private void setMsgtype(int value) {
      bitField0_ |= 0x00000002;
      msgtype_ = value;
    }
    /**
     * <code>required int32 msgtype = 2;</code>
     */
    private void clearMsgtype() {
      bitField0_ = (bitField0_ & ~0x00000002);
      msgtype_ = 0;
    }

    public static final int MSGSEQ_FIELD_NUMBER = 3;
    private int msgseq_;
    /**
     * <code>required int32 msgseq = 3;</code>
     */
    public boolean hasMsgseq() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 msgseq = 3;</code>
     */
    public int getMsgseq() {
      return msgseq_;
    }
    /**
     * <code>required int32 msgseq = 3;</code>
     */
    private void setMsgseq(int value) {
      bitField0_ |= 0x00000004;
      msgseq_ = value;
    }
    /**
     * <code>required int32 msgseq = 3;</code>
     */
    private void clearMsgseq() {
      bitField0_ = (bitField0_ & ~0x00000004);
      msgseq_ = 0;
    }

    public static final int TERMVERSION_FIELD_NUMBER = 4;
    private int termversion_;
    /**
     * <code>required int32 termversion = 4;</code>
     */
    public boolean hasTermversion() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 termversion = 4;</code>
     */
    public int getTermversion() {
      return termversion_;
    }
    /**
     * <code>required int32 termversion = 4;</code>
     */
    private void setTermversion(int value) {
      bitField0_ |= 0x00000008;
      termversion_ = value;
    }
    /**
     * <code>required int32 termversion = 4;</code>
     */
    private void clearTermversion() {
      bitField0_ = (bitField0_ & ~0x00000008);
      termversion_ = 0;
    }

    public static final int MSGRES_FIELD_NUMBER = 5;
    private int msgres_;
    /**
     * <code>required int32 msgres = 5;</code>
     */
    public boolean hasMsgres() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 msgres = 5;</code>
     */
    public int getMsgres() {
      return msgres_;
    }
    /**
     * <code>required int32 msgres = 5;</code>
     */
    private void setMsgres(int value) {
      bitField0_ |= 0x00000010;
      msgres_ = value;
    }
    /**
     * <code>required int32 msgres = 5;</code>
     */
    private void clearMsgres() {
      bitField0_ = (bitField0_ & ~0x00000010);
      msgres_ = 0;
    }

    public static final int TERMID_FIELD_NUMBER = 6;
    private java.lang.String termid_;
    /**
     * <code>required string termid = 6;</code>
     */
    public boolean hasTermid() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string termid = 6;</code>
     */
    public java.lang.String getTermid() {
      return termid_;
    }
    /**
     * <code>required string termid = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTermidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(termid_);
    }
    /**
     * <code>required string termid = 6;</code>
     */
    private void setTermid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      termid_ = value;
    }
    /**
     * <code>required string termid = 6;</code>
     */
    private void clearTermid() {
      bitField0_ = (bitField0_ & ~0x00000020);
      termid_ = getDefaultInstance().getTermid();
    }
    /**
     * <code>required string termid = 6;</code>
     */
    private void setTermidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      termid_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msglen_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, msgtype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, msgseq_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, termversion_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, msgres_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeString(6, getTermid());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msglen_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, msgtype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, msgseq_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, termversion_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, msgres_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getTermid());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static Msg.CMsgHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Msg.CMsgHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Msg.CMsgHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Msg.CMsgHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Msg.CMsgHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Msg.CMsgHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Msg.CMsgHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Msg.CMsgHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Msg.CMsgHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Msg.CMsgHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Msg.CMsgHead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code CMsgHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Msg.CMsgHead, Builder> implements
        // @@protoc_insertion_point(builder_implements:CMsgHead)
        Msg.CMsgHeadOrBuilder {
      // Construct using Msg.CMsgHead.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 msglen = 1;</code>
       */
      public boolean hasMsglen() {
        return instance.hasMsglen();
      }
      /**
       * <code>required int32 msglen = 1;</code>
       */
      public int getMsglen() {
        return instance.getMsglen();
      }
      /**
       * <code>required int32 msglen = 1;</code>
       */
      public Builder setMsglen(int value) {
        copyOnWrite();
        instance.setMsglen(value);
        return this;
      }
      /**
       * <code>required int32 msglen = 1;</code>
       */
      public Builder clearMsglen() {
        copyOnWrite();
        instance.clearMsglen();
        return this;
      }

      /**
       * <code>required int32 msgtype = 2;</code>
       */
      public boolean hasMsgtype() {
        return instance.hasMsgtype();
      }
      /**
       * <code>required int32 msgtype = 2;</code>
       */
      public int getMsgtype() {
        return instance.getMsgtype();
      }
      /**
       * <code>required int32 msgtype = 2;</code>
       */
      public Builder setMsgtype(int value) {
        copyOnWrite();
        instance.setMsgtype(value);
        return this;
      }
      /**
       * <code>required int32 msgtype = 2;</code>
       */
      public Builder clearMsgtype() {
        copyOnWrite();
        instance.clearMsgtype();
        return this;
      }

      /**
       * <code>required int32 msgseq = 3;</code>
       */
      public boolean hasMsgseq() {
        return instance.hasMsgseq();
      }
      /**
       * <code>required int32 msgseq = 3;</code>
       */
      public int getMsgseq() {
        return instance.getMsgseq();
      }
      /**
       * <code>required int32 msgseq = 3;</code>
       */
      public Builder setMsgseq(int value) {
        copyOnWrite();
        instance.setMsgseq(value);
        return this;
      }
      /**
       * <code>required int32 msgseq = 3;</code>
       */
      public Builder clearMsgseq() {
        copyOnWrite();
        instance.clearMsgseq();
        return this;
      }

      /**
       * <code>required int32 termversion = 4;</code>
       */
      public boolean hasTermversion() {
        return instance.hasTermversion();
      }
      /**
       * <code>required int32 termversion = 4;</code>
       */
      public int getTermversion() {
        return instance.getTermversion();
      }
      /**
       * <code>required int32 termversion = 4;</code>
       */
      public Builder setTermversion(int value) {
        copyOnWrite();
        instance.setTermversion(value);
        return this;
      }
      /**
       * <code>required int32 termversion = 4;</code>
       */
      public Builder clearTermversion() {
        copyOnWrite();
        instance.clearTermversion();
        return this;
      }

      /**
       * <code>required int32 msgres = 5;</code>
       */
      public boolean hasMsgres() {
        return instance.hasMsgres();
      }
      /**
       * <code>required int32 msgres = 5;</code>
       */
      public int getMsgres() {
        return instance.getMsgres();
      }
      /**
       * <code>required int32 msgres = 5;</code>
       */
      public Builder setMsgres(int value) {
        copyOnWrite();
        instance.setMsgres(value);
        return this;
      }
      /**
       * <code>required int32 msgres = 5;</code>
       */
      public Builder clearMsgres() {
        copyOnWrite();
        instance.clearMsgres();
        return this;
      }

      /**
       * <code>required string termid = 6;</code>
       */
      public boolean hasTermid() {
        return instance.hasTermid();
      }
      /**
       * <code>required string termid = 6;</code>
       */
      public java.lang.String getTermid() {
        return instance.getTermid();
      }
      /**
       * <code>required string termid = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTermidBytes() {
        return instance.getTermidBytes();
      }
      /**
       * <code>required string termid = 6;</code>
       */
      public Builder setTermid(
          java.lang.String value) {
        copyOnWrite();
        instance.setTermid(value);
        return this;
      }
      /**
       * <code>required string termid = 6;</code>
       */
      public Builder clearTermid() {
        copyOnWrite();
        instance.clearTermid();
        return this;
      }
      /**
       * <code>required string termid = 6;</code>
       */
      public Builder setTermidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTermidBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CMsgHead)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Msg.CMsgHead();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasMsglen()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasMsgtype()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasMsgseq()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasTermversion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasMsgres()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasTermid()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Msg.CMsgHead other = (Msg.CMsgHead) arg1;
          msglen_ = visitor.visitInt(
              hasMsglen(), msglen_,
              other.hasMsglen(), other.msglen_);
          msgtype_ = visitor.visitInt(
              hasMsgtype(), msgtype_,
              other.hasMsgtype(), other.msgtype_);
          msgseq_ = visitor.visitInt(
              hasMsgseq(), msgseq_,
              other.hasMsgseq(), other.msgseq_);
          termversion_ = visitor.visitInt(
              hasTermversion(), termversion_,
              other.hasTermversion(), other.termversion_);
          msgres_ = visitor.visitInt(
              hasMsgres(), msgres_,
              other.hasMsgres(), other.msgres_);
          termid_ = visitor.visitString(
              hasTermid(), termid_,
              other.hasTermid(), other.termid_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  msglen_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  msgtype_ = input.readInt32();
                  break;
                }
                case 24: {
                  bitField0_ |= 0x00000004;
                  msgseq_ = input.readInt32();
                  break;
                }
                case 32: {
                  bitField0_ |= 0x00000008;
                  termversion_ = input.readInt32();
                  break;
                }
                case 40: {
                  bitField0_ |= 0x00000010;
                  msgres_ = input.readInt32();
                  break;
                }
                case 50: {
                  String s = input.readString();
                  bitField0_ |= 0x00000020;
                  termid_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Msg.CMsgHead.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CMsgHead)
    private static final Msg.CMsgHead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CMsgHead();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Msg.CMsgHead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CMsgHead> PARSER;

    public static com.google.protobuf.Parser<CMsgHead> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CMsgRegOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CMsgReg)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 area = 1;</code>
     */
    boolean hasArea();
    /**
     * <code>optional int32 area = 1;</code>
     */
    int getArea();

    /**
     * <code>optional int32 region = 2;</code>
     */
    boolean hasRegion();
    /**
     * <code>optional int32 region = 2;</code>
     */
    int getRegion();

    /**
     * <code>optional int32 shop = 3;</code>
     */
    boolean hasShop();
    /**
     * <code>optional int32 shop = 3;</code>
     */
    int getShop();

    /**
     * <code>optional int32 ret = 4;</code>
     */
    boolean hasRet();
    /**
     * <code>optional int32 ret = 4;</code>
     */
    int getRet();

    /**
     * <code>optional string termid = 5;</code>
     */
    boolean hasTermid();
    /**
     * <code>optional string termid = 5;</code>
     */
    java.lang.String getTermid();
    /**
     * <code>optional string termid = 5;</code>
     */
    com.google.protobuf.ByteString
        getTermidBytes();
  }
  /**
   * Protobuf type {@code CMsgReg}
   */
  public  static final class CMsgReg extends
      com.google.protobuf.GeneratedMessageLite<
          CMsgReg, CMsgReg.Builder> implements
      // @@protoc_insertion_point(message_implements:CMsgReg)
      CMsgRegOrBuilder {
    private CMsgReg() {
      termid_ = "";
    }
    private int bitField0_;
    public static final int AREA_FIELD_NUMBER = 1;
    private int area_;
    /**
     * <code>optional int32 area = 1;</code>
     */
    public boolean hasArea() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 area = 1;</code>
     */
    public int getArea() {
      return area_;
    }
    /**
     * <code>optional int32 area = 1;</code>
     */
    private void setArea(int value) {
      bitField0_ |= 0x00000001;
      area_ = value;
    }
    /**
     * <code>optional int32 area = 1;</code>
     */
    private void clearArea() {
      bitField0_ = (bitField0_ & ~0x00000001);
      area_ = 0;
    }

    public static final int REGION_FIELD_NUMBER = 2;
    private int region_;
    /**
     * <code>optional int32 region = 2;</code>
     */
    public boolean hasRegion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 region = 2;</code>
     */
    public int getRegion() {
      return region_;
    }
    /**
     * <code>optional int32 region = 2;</code>
     */
    private void setRegion(int value) {
      bitField0_ |= 0x00000002;
      region_ = value;
    }
    /**
     * <code>optional int32 region = 2;</code>
     */
    private void clearRegion() {
      bitField0_ = (bitField0_ & ~0x00000002);
      region_ = 0;
    }

    public static final int SHOP_FIELD_NUMBER = 3;
    private int shop_;
    /**
     * <code>optional int32 shop = 3;</code>
     */
    public boolean hasShop() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 shop = 3;</code>
     */
    public int getShop() {
      return shop_;
    }
    /**
     * <code>optional int32 shop = 3;</code>
     */
    private void setShop(int value) {
      bitField0_ |= 0x00000004;
      shop_ = value;
    }
    /**
     * <code>optional int32 shop = 3;</code>
     */
    private void clearShop() {
      bitField0_ = (bitField0_ & ~0x00000004);
      shop_ = 0;
    }

    public static final int RET_FIELD_NUMBER = 4;
    private int ret_;
    /**
     * <code>optional int32 ret = 4;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 ret = 4;</code>
     */
    public int getRet() {
      return ret_;
    }
    /**
     * <code>optional int32 ret = 4;</code>
     */
    private void setRet(int value) {
      bitField0_ |= 0x00000008;
      ret_ = value;
    }
    /**
     * <code>optional int32 ret = 4;</code>
     */
    private void clearRet() {
      bitField0_ = (bitField0_ & ~0x00000008);
      ret_ = 0;
    }

    public static final int TERMID_FIELD_NUMBER = 5;
    private java.lang.String termid_;
    /**
     * <code>optional string termid = 5;</code>
     */
    public boolean hasTermid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string termid = 5;</code>
     */
    public java.lang.String getTermid() {
      return termid_;
    }
    /**
     * <code>optional string termid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTermidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(termid_);
    }
    /**
     * <code>optional string termid = 5;</code>
     */
    private void setTermid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      termid_ = value;
    }
    /**
     * <code>optional string termid = 5;</code>
     */
    private void clearTermid() {
      bitField0_ = (bitField0_ & ~0x00000010);
      termid_ = getDefaultInstance().getTermid();
    }
    /**
     * <code>optional string termid = 5;</code>
     */
    private void setTermidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      termid_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, area_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, region_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, shop_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, ret_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeString(5, getTermid());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, area_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, region_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, shop_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ret_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getTermid());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static Msg.CMsgReg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Msg.CMsgReg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Msg.CMsgReg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Msg.CMsgReg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Msg.CMsgReg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Msg.CMsgReg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Msg.CMsgReg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Msg.CMsgReg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Msg.CMsgReg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Msg.CMsgReg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Msg.CMsgReg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code CMsgReg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Msg.CMsgReg, Builder> implements
        // @@protoc_insertion_point(builder_implements:CMsgReg)
        Msg.CMsgRegOrBuilder {
      // Construct using Msg.CMsgReg.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 area = 1;</code>
       */
      public boolean hasArea() {
        return instance.hasArea();
      }
      /**
       * <code>optional int32 area = 1;</code>
       */
      public int getArea() {
        return instance.getArea();
      }
      /**
       * <code>optional int32 area = 1;</code>
       */
      public Builder setArea(int value) {
        copyOnWrite();
        instance.setArea(value);
        return this;
      }
      /**
       * <code>optional int32 area = 1;</code>
       */
      public Builder clearArea() {
        copyOnWrite();
        instance.clearArea();
        return this;
      }

      /**
       * <code>optional int32 region = 2;</code>
       */
      public boolean hasRegion() {
        return instance.hasRegion();
      }
      /**
       * <code>optional int32 region = 2;</code>
       */
      public int getRegion() {
        return instance.getRegion();
      }
      /**
       * <code>optional int32 region = 2;</code>
       */
      public Builder setRegion(int value) {
        copyOnWrite();
        instance.setRegion(value);
        return this;
      }
      /**
       * <code>optional int32 region = 2;</code>
       */
      public Builder clearRegion() {
        copyOnWrite();
        instance.clearRegion();
        return this;
      }

      /**
       * <code>optional int32 shop = 3;</code>
       */
      public boolean hasShop() {
        return instance.hasShop();
      }
      /**
       * <code>optional int32 shop = 3;</code>
       */
      public int getShop() {
        return instance.getShop();
      }
      /**
       * <code>optional int32 shop = 3;</code>
       */
      public Builder setShop(int value) {
        copyOnWrite();
        instance.setShop(value);
        return this;
      }
      /**
       * <code>optional int32 shop = 3;</code>
       */
      public Builder clearShop() {
        copyOnWrite();
        instance.clearShop();
        return this;
      }

      /**
       * <code>optional int32 ret = 4;</code>
       */
      public boolean hasRet() {
        return instance.hasRet();
      }
      /**
       * <code>optional int32 ret = 4;</code>
       */
      public int getRet() {
        return instance.getRet();
      }
      /**
       * <code>optional int32 ret = 4;</code>
       */
      public Builder setRet(int value) {
        copyOnWrite();
        instance.setRet(value);
        return this;
      }
      /**
       * <code>optional int32 ret = 4;</code>
       */
      public Builder clearRet() {
        copyOnWrite();
        instance.clearRet();
        return this;
      }

      /**
       * <code>optional string termid = 5;</code>
       */
      public boolean hasTermid() {
        return instance.hasTermid();
      }
      /**
       * <code>optional string termid = 5;</code>
       */
      public java.lang.String getTermid() {
        return instance.getTermid();
      }
      /**
       * <code>optional string termid = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTermidBytes() {
        return instance.getTermidBytes();
      }
      /**
       * <code>optional string termid = 5;</code>
       */
      public Builder setTermid(
          java.lang.String value) {
        copyOnWrite();
        instance.setTermid(value);
        return this;
      }
      /**
       * <code>optional string termid = 5;</code>
       */
      public Builder clearTermid() {
        copyOnWrite();
        instance.clearTermid();
        return this;
      }
      /**
       * <code>optional string termid = 5;</code>
       */
      public Builder setTermidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTermidBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CMsgReg)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Msg.CMsgReg();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Msg.CMsgReg other = (Msg.CMsgReg) arg1;
          area_ = visitor.visitInt(
              hasArea(), area_,
              other.hasArea(), other.area_);
          region_ = visitor.visitInt(
              hasRegion(), region_,
              other.hasRegion(), other.region_);
          shop_ = visitor.visitInt(
              hasShop(), shop_,
              other.hasShop(), other.shop_);
          ret_ = visitor.visitInt(
              hasRet(), ret_,
              other.hasRet(), other.ret_);
          termid_ = visitor.visitString(
              hasTermid(), termid_,
              other.hasTermid(), other.termid_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  area_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  region_ = input.readInt32();
                  break;
                }
                case 24: {
                  bitField0_ |= 0x00000004;
                  shop_ = input.readInt32();
                  break;
                }
                case 32: {
                  bitField0_ |= 0x00000008;
                  ret_ = input.readInt32();
                  break;
                }
                case 42: {
                  String s = input.readString();
                  bitField0_ |= 0x00000010;
                  termid_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Msg.CMsgReg.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CMsgReg)
    private static final Msg.CMsgReg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CMsgReg();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Msg.CMsgReg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CMsgReg> PARSER;

    public static com.google.protobuf.Parser<CMsgReg> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
