// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/PVPSerProtocol.proto

package com.dsky.netty.pvpser.protocode;

public final class PVPSerProtocol {
  private PVPSerProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SocketRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SocketRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 number = 1;</code>
     */
    boolean hasNumber();
    /**
     * <code>required int32 number = 1;</code>
     */
    int getNumber();

    /**
     * <code>required int32 sequence = 2;</code>
     */
    boolean hasSequence();
    /**
     * <code>required int32 sequence = 2;</code>
     */
    int getSequence();

    /**
     * <code>optional int32 reserve = 3;</code>
     */
    boolean hasReserve();
    /**
     * <code>optional int32 reserve = 3;</code>
     */
    int getReserve();

    /**
     * <code>optional string requestMsg = 4;</code>
     */
    boolean hasRequestMsg();
    /**
     * <code>optional string requestMsg = 4;</code>
     */
    java.lang.String getRequestMsg();
    /**
     * <code>optional string requestMsg = 4;</code>
     */
    com.google.protobuf.ByteString
        getRequestMsgBytes();
  }
  /**
   * Protobuf type {@code SocketRequest}
   */
  public  static final class SocketRequest extends
      com.google.protobuf.GeneratedMessageLite<
          SocketRequest, SocketRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:SocketRequest)
      SocketRequestOrBuilder {
    private SocketRequest() {
      requestMsg_ = "";
    }
    private int bitField0_;
    public static final int NUMBER_FIELD_NUMBER = 1;
    private int number_;
    /**
     * <code>required int32 number = 1;</code>
     */
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 number = 1;</code>
     */
    public int getNumber() {
      return number_;
    }
    /**
     * <code>required int32 number = 1;</code>
     */
    private void setNumber(int value) {
      bitField0_ |= 0x00000001;
      number_ = value;
    }
    /**
     * <code>required int32 number = 1;</code>
     */
    private void clearNumber() {
      bitField0_ = (bitField0_ & ~0x00000001);
      number_ = 0;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 2;
    private int sequence_;
    /**
     * <code>required int32 sequence = 2;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 sequence = 2;</code>
     */
    public int getSequence() {
      return sequence_;
    }
    /**
     * <code>required int32 sequence = 2;</code>
     */
    private void setSequence(int value) {
      bitField0_ |= 0x00000002;
      sequence_ = value;
    }
    /**
     * <code>required int32 sequence = 2;</code>
     */
    private void clearSequence() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sequence_ = 0;
    }

    public static final int RESERVE_FIELD_NUMBER = 3;
    private int reserve_;
    /**
     * <code>optional int32 reserve = 3;</code>
     */
    public boolean hasReserve() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 reserve = 3;</code>
     */
    public int getReserve() {
      return reserve_;
    }
    /**
     * <code>optional int32 reserve = 3;</code>
     */
    private void setReserve(int value) {
      bitField0_ |= 0x00000004;
      reserve_ = value;
    }
    /**
     * <code>optional int32 reserve = 3;</code>
     */
    private void clearReserve() {
      bitField0_ = (bitField0_ & ~0x00000004);
      reserve_ = 0;
    }

    public static final int REQUESTMSG_FIELD_NUMBER = 4;
    private java.lang.String requestMsg_;
    /**
     * <code>optional string requestMsg = 4;</code>
     */
    public boolean hasRequestMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string requestMsg = 4;</code>
     */
    public java.lang.String getRequestMsg() {
      return requestMsg_;
    }
    /**
     * <code>optional string requestMsg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRequestMsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(requestMsg_);
    }
    /**
     * <code>optional string requestMsg = 4;</code>
     */
    private void setRequestMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      requestMsg_ = value;
    }
    /**
     * <code>optional string requestMsg = 4;</code>
     */
    private void clearRequestMsg() {
      bitField0_ = (bitField0_ & ~0x00000008);
      requestMsg_ = getDefaultInstance().getRequestMsg();
    }
    /**
     * <code>optional string requestMsg = 4;</code>
     */
    private void setRequestMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      requestMsg_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, number_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, reserve_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeString(4, getRequestMsg());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, number_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, reserve_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getRequestMsg());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code SocketRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:SocketRequest)
        com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequestOrBuilder {
      // Construct using com.dsky.netty.protocode.PVPSerProtocol.SocketRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 number = 1;</code>
       */
      public boolean hasNumber() {
        return instance.hasNumber();
      }
      /**
       * <code>required int32 number = 1;</code>
       */
      public int getNumber() {
        return instance.getNumber();
      }
      /**
       * <code>required int32 number = 1;</code>
       */
      public Builder setNumber(int value) {
        copyOnWrite();
        instance.setNumber(value);
        return this;
      }
      /**
       * <code>required int32 number = 1;</code>
       */
      public Builder clearNumber() {
        copyOnWrite();
        instance.clearNumber();
        return this;
      }

      /**
       * <code>required int32 sequence = 2;</code>
       */
      public boolean hasSequence() {
        return instance.hasSequence();
      }
      /**
       * <code>required int32 sequence = 2;</code>
       */
      public int getSequence() {
        return instance.getSequence();
      }
      /**
       * <code>required int32 sequence = 2;</code>
       */
      public Builder setSequence(int value) {
        copyOnWrite();
        instance.setSequence(value);
        return this;
      }
      /**
       * <code>required int32 sequence = 2;</code>
       */
      public Builder clearSequence() {
        copyOnWrite();
        instance.clearSequence();
        return this;
      }

      /**
       * <code>optional int32 reserve = 3;</code>
       */
      public boolean hasReserve() {
        return instance.hasReserve();
      }
      /**
       * <code>optional int32 reserve = 3;</code>
       */
      public int getReserve() {
        return instance.getReserve();
      }
      /**
       * <code>optional int32 reserve = 3;</code>
       */
      public Builder setReserve(int value) {
        copyOnWrite();
        instance.setReserve(value);
        return this;
      }
      /**
       * <code>optional int32 reserve = 3;</code>
       */
      public Builder clearReserve() {
        copyOnWrite();
        instance.clearReserve();
        return this;
      }

      /**
       * <code>optional string requestMsg = 4;</code>
       */
      public boolean hasRequestMsg() {
        return instance.hasRequestMsg();
      }
      /**
       * <code>optional string requestMsg = 4;</code>
       */
      public java.lang.String getRequestMsg() {
        return instance.getRequestMsg();
      }
      /**
       * <code>optional string requestMsg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRequestMsgBytes() {
        return instance.getRequestMsgBytes();
      }
      /**
       * <code>optional string requestMsg = 4;</code>
       */
      public Builder setRequestMsg(
          java.lang.String value) {
        copyOnWrite();
        instance.setRequestMsg(value);
        return this;
      }
      /**
       * <code>optional string requestMsg = 4;</code>
       */
      public Builder clearRequestMsg() {
        copyOnWrite();
        instance.clearRequestMsg();
        return this;
      }
      /**
       * <code>optional string requestMsg = 4;</code>
       */
      public Builder setRequestMsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRequestMsgBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SocketRequest)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasNumber()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasSequence()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest other = (com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest) arg1;
          number_ = visitor.visitInt(
              hasNumber(), number_,
              other.hasNumber(), other.number_);
          sequence_ = visitor.visitInt(
              hasSequence(), sequence_,
              other.hasSequence(), other.sequence_);
          reserve_ = visitor.visitInt(
              hasReserve(), reserve_,
              other.hasReserve(), other.reserve_);
          requestMsg_ = visitor.visitString(
              hasRequestMsg(), requestMsg_,
              other.hasRequestMsg(), other.requestMsg_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  number_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  sequence_ = input.readInt32();
                  break;
                }
                case 24: {
                  bitField0_ |= 0x00000004;
                  reserve_ = input.readInt32();
                  break;
                }
                case 34: {
                  String s = input.readString();
                  bitField0_ |= 0x00000008;
                  requestMsg_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SocketRequest)
    private static final com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SocketRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SocketRequest> PARSER;

    public static com.google.protobuf.Parser<SocketRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SocketResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SocketResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 number = 1;</code>
     */
    boolean hasNumber();
    /**
     * <code>required int32 number = 1;</code>
     */
    int getNumber();

    /**
     * <code>required int32 sequence = 2;</code>
     */
    boolean hasSequence();
    /**
     * <code>required int32 sequence = 2;</code>
     */
    int getSequence();

    /**
     * <code>optional int32 reserve = 3;</code>
     */
    boolean hasReserve();
    /**
     * <code>optional int32 reserve = 3;</code>
     */
    int getReserve();

    /**
     * <code>optional string responseMsg = 4;</code>
     */
    boolean hasResponseMsg();
    /**
     * <code>optional string responseMsg = 4;</code>
     */
    java.lang.String getResponseMsg();
    /**
     * <code>optional string responseMsg = 4;</code>
     */
    com.google.protobuf.ByteString
        getResponseMsgBytes();
  }
  /**
   * Protobuf type {@code SocketResponse}
   */
  public  static final class SocketResponse extends
      com.google.protobuf.GeneratedMessageLite<
          SocketResponse, SocketResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:SocketResponse)
      SocketResponseOrBuilder {
    private SocketResponse() {
      responseMsg_ = "";
    }
    private int bitField0_;
    public static final int NUMBER_FIELD_NUMBER = 1;
    private int number_;
    /**
     * <code>required int32 number = 1;</code>
     */
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 number = 1;</code>
     */
    public int getNumber() {
      return number_;
    }
    /**
     * <code>required int32 number = 1;</code>
     */
    private void setNumber(int value) {
      bitField0_ |= 0x00000001;
      number_ = value;
    }
    /**
     * <code>required int32 number = 1;</code>
     */
    private void clearNumber() {
      bitField0_ = (bitField0_ & ~0x00000001);
      number_ = 0;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 2;
    private int sequence_;
    /**
     * <code>required int32 sequence = 2;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 sequence = 2;</code>
     */
    public int getSequence() {
      return sequence_;
    }
    /**
     * <code>required int32 sequence = 2;</code>
     */
    private void setSequence(int value) {
      bitField0_ |= 0x00000002;
      sequence_ = value;
    }
    /**
     * <code>required int32 sequence = 2;</code>
     */
    private void clearSequence() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sequence_ = 0;
    }

    public static final int RESERVE_FIELD_NUMBER = 3;
    private int reserve_;
    /**
     * <code>optional int32 reserve = 3;</code>
     */
    public boolean hasReserve() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 reserve = 3;</code>
     */
    public int getReserve() {
      return reserve_;
    }
    /**
     * <code>optional int32 reserve = 3;</code>
     */
    private void setReserve(int value) {
      bitField0_ |= 0x00000004;
      reserve_ = value;
    }
    /**
     * <code>optional int32 reserve = 3;</code>
     */
    private void clearReserve() {
      bitField0_ = (bitField0_ & ~0x00000004);
      reserve_ = 0;
    }

    public static final int RESPONSEMSG_FIELD_NUMBER = 4;
    private java.lang.String responseMsg_;
    /**
     * <code>optional string responseMsg = 4;</code>
     */
    public boolean hasResponseMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string responseMsg = 4;</code>
     */
    public java.lang.String getResponseMsg() {
      return responseMsg_;
    }
    /**
     * <code>optional string responseMsg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(responseMsg_);
    }
    /**
     * <code>optional string responseMsg = 4;</code>
     */
    private void setResponseMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      responseMsg_ = value;
    }
    /**
     * <code>optional string responseMsg = 4;</code>
     */
    private void clearResponseMsg() {
      bitField0_ = (bitField0_ & ~0x00000008);
      responseMsg_ = getDefaultInstance().getResponseMsg();
    }
    /**
     * <code>optional string responseMsg = 4;</code>
     */
    private void setResponseMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      responseMsg_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, number_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, reserve_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeString(4, getResponseMsg());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, number_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, reserve_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getResponseMsg());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code SocketResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:SocketResponse)
        com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponseOrBuilder {
      // Construct using com.dsky.netty.protocode.PVPSerProtocol.SocketResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 number = 1;</code>
       */
      public boolean hasNumber() {
        return instance.hasNumber();
      }
      /**
       * <code>required int32 number = 1;</code>
       */
      public int getNumber() {
        return instance.getNumber();
      }
      /**
       * <code>required int32 number = 1;</code>
       */
      public Builder setNumber(int value) {
        copyOnWrite();
        instance.setNumber(value);
        return this;
      }
      /**
       * <code>required int32 number = 1;</code>
       */
      public Builder clearNumber() {
        copyOnWrite();
        instance.clearNumber();
        return this;
      }

      /**
       * <code>required int32 sequence = 2;</code>
       */
      public boolean hasSequence() {
        return instance.hasSequence();
      }
      /**
       * <code>required int32 sequence = 2;</code>
       */
      public int getSequence() {
        return instance.getSequence();
      }
      /**
       * <code>required int32 sequence = 2;</code>
       */
      public Builder setSequence(int value) {
        copyOnWrite();
        instance.setSequence(value);
        return this;
      }
      /**
       * <code>required int32 sequence = 2;</code>
       */
      public Builder clearSequence() {
        copyOnWrite();
        instance.clearSequence();
        return this;
      }

      /**
       * <code>optional int32 reserve = 3;</code>
       */
      public boolean hasReserve() {
        return instance.hasReserve();
      }
      /**
       * <code>optional int32 reserve = 3;</code>
       */
      public int getReserve() {
        return instance.getReserve();
      }
      /**
       * <code>optional int32 reserve = 3;</code>
       */
      public Builder setReserve(int value) {
        copyOnWrite();
        instance.setReserve(value);
        return this;
      }
      /**
       * <code>optional int32 reserve = 3;</code>
       */
      public Builder clearReserve() {
        copyOnWrite();
        instance.clearReserve();
        return this;
      }

      /**
       * <code>optional string responseMsg = 4;</code>
       */
      public boolean hasResponseMsg() {
        return instance.hasResponseMsg();
      }
      /**
       * <code>optional string responseMsg = 4;</code>
       */
      public java.lang.String getResponseMsg() {
        return instance.getResponseMsg();
      }
      /**
       * <code>optional string responseMsg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMsgBytes() {
        return instance.getResponseMsgBytes();
      }
      /**
       * <code>optional string responseMsg = 4;</code>
       */
      public Builder setResponseMsg(
          java.lang.String value) {
        copyOnWrite();
        instance.setResponseMsg(value);
        return this;
      }
      /**
       * <code>optional string responseMsg = 4;</code>
       */
      public Builder clearResponseMsg() {
        copyOnWrite();
        instance.clearResponseMsg();
        return this;
      }
      /**
       * <code>optional string responseMsg = 4;</code>
       */
      public Builder setResponseMsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setResponseMsgBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SocketResponse)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasNumber()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasSequence()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse other = (com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse) arg1;
          number_ = visitor.visitInt(
              hasNumber(), number_,
              other.hasNumber(), other.number_);
          sequence_ = visitor.visitInt(
              hasSequence(), sequence_,
              other.hasSequence(), other.sequence_);
          reserve_ = visitor.visitInt(
              hasReserve(), reserve_,
              other.hasReserve(), other.reserve_);
          responseMsg_ = visitor.visitString(
              hasResponseMsg(), responseMsg_,
              other.hasResponseMsg(), other.responseMsg_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  number_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  sequence_ = input.readInt32();
                  break;
                }
                case 24: {
                  bitField0_ |= 0x00000004;
                  reserve_ = input.readInt32();
                  break;
                }
                case 34: {
                  String s = input.readString();
                  bitField0_ |= 0x00000008;
                  responseMsg_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SocketResponse)
    private static final com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SocketResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.dsky.netty.pvpser.protocode.PVPSerProtocol.SocketResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SocketResponse> PARSER;

    public static com.google.protobuf.Parser<SocketResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
